#!/bin/bash
#
# Generates minutes for the directory given

display_usage() { 
	echo "Publish CCG minutes via email and social media." 
	echo ""
	echo "Usage: ./publish [-h] [-d directory]" 
	echo "  -d [/path/to/YYYY-MM-DD]     generate minutes for directory/date"
    echo "  -h                           display help"
    echo ""
    echo "Examples:"
	echo ""
    echo "  ./publish -d /path/to/w3c-ccg-meeting/2018-05-15" 
    echo "      generates minutes for specified date and commits to git"   
    echo ""
} 


if [ $# -eq 0 ]
  then
    display_usage
    exit 1
else
	for i in "$@"
	do
	case $i in
		--)
	    display_usage
	    exit 0
	    ;;
	    -h|--help)
	    display_usage
	    exit 0
	    ;;
	    -d|--directory)
		shift
	    DIRECTORY=$1
	    break
	    ;;
	esac
	done
fi

echo "....Running publishing script for directory=$DIRECTORY"

DATE="$(basename $DIRECTORY)"

source ../publishing.cfg

# Add default values for missing env vars
if [ -z "$NODE_COMMAND" ]; then
    NODE_COMMAND="nodejs"
fi 

echo "Generating minutes for $DATE"
MESSAGE="Add text minutes and audio logs for $DATE telecon."

# Generate minutes
$NODE_COMMAND index.js -d $DIRECTORY -m -i

# Make sure we want to continue
read -r -p "Check for problems, press 'y' when ready to commit to git: " BROADCAST

echo "Broadcast: $BROADCAST"

if [ "$BROADCAST" != "y" ]
then
   echo "Aborting git commit and social media broadcast."
   exit
fi

echo "Add text minutes and audio logs for $DATE telecon."

git add $DIRECTORY/irc.log $DIRECTORY/index.html $DIRECTORY/audio.ogg
git commit $DIRECTORY/irc.log $DIRECTORY/index.html $DIRECTORY/audio.ogg $DIRECTORY/../index.html -m "$MESSAGE"
git push


